- badge_store/main.py
- lib/dialogs.py
- lib/sleep.py
- lib/stack_nav.py
- lib/wifi.py
- settings/badge_store_settings.py
- settings/main.py
A simple settings app that allows users to
* change their name (as displayed on the homescreen)
* change wifi details
* change badge store settings
* pick a startup app
I've wrapped some of the common functionality into a lib - I'm planning to roll it out to the badge store as well, since it has a similar navigation structure
Fixes https://github.com/emfcamp/Mk4-Apps/issues/5
> Settings app

- settings/main.py
Homescreeen has too many eeeeees
> Fix typo in settings menu

- .development/pyboard_util.py
- .development/resources.py
> Fix tilda_tools test not working in Windows

- dowsingrod/main.py
This may be too specific? But: this will print a list of signal strengths and MAC addresses of any nearby APs advertising `emfcamp-legacy18`.
> WiFi Dowsing Rod

- game-of-life/main.py
Haven't had my badge yet so couldn't test for real, let's hope it works :laughing:
> Game of life - 1st draft

- square_home/main.py
An attempt at a home screen with a spinning and squares.
> Add a home screen with spinning squares

- LED_Party/main.py
It said press B to quit which was wrong
> Fixed incorrect instruction

- breakout/main.py
Use the left and right buttons on the D-pad to play.
> Breakout game

- memobadge/main.py
The most incredible dictaphone ever. 
🎉
> Add a memorable dictaphone

- pride/main.py
Pride flag homescreen is very similar to the default homescreen except the background is a pride flag.
> Added pride flag homescreen

- lib/dialogs.py
Reduces flicker in launcher app
> Disable redraw while populating prompt_option list

- lib/dialogs.py
Enables text entry via the keypad in text input dialogs, for that old-skool text input experience.
> Multitap keypad text entry

- warm_and_wet/main.py
This app displays the temperature and humidity readings as text and a scrolling chart. It has a hard coded 10 degrees C offset based on BBC weather app values last night - this needs to be improved (along with many other things)!
> First submission of temp and humidity sensor data display app

- enby/main.py
Add enby (non binary) flag colours to homescreen.
> add enby flag homescreen

- mario/main.py
Hi EMF Badge Team ! 
I was able to talk to Jon this morning and get a Tilda Mk4. 
I said I would definitely dev an app and push it to EMF Repo. 
I have got a good sounding version of the Mario theme, and it pulls a photo of Mario and the Mushroom down. 
There are some TODOs: 
Implement a break to exit the app if a user pushes any button whilst playing. 
Gracefully reboot into main menu on Menu Press. 
Replay Track when user pushes a button.
> App : Plays the Mario theme, Displays picture of Mario. 

- lib/dialogs.py
Using * and #. Also made 0-9 jump to that item.
> Added page up and page down to prompt_option dialogs

- home_stratum0/main.py
> Fix sleep_or_exit timer. Set to default (0.5)

- btscan/main.py
- lib/sim800.py
Includes fix for sim800.btscan where only the last detected device would be returned
> BTScan - Bluetooth device scan app

- party/main.py
Adds a "party" app that just randomly flashes the Neopix LEDs :)
> Adds party app

- avatar/main.py
Also changes the license to something more appropriate.
> Fixed avatar homescreen app category

- SketchyEtch/main.py
Added option to clear drawing, added initial dialog with instructions, added ability to create circles
> Updated Sketchy-Etch

- bluetooth_speaker/main.py
A simple bluetooth speaker application, with hardcoded pin etc. 
Works on OSX, some issues with forcing android to use it for music, but still works as a headset.
> Add app to use badge as bluetooth speaker

- pride/main.py
Added a selection of flags for the user to choose from, as well as a few code/render improvements.
> Pride add selection of flags

- DevRant/main.py
Text only DevRant client, only for viewing. Currently no posting or ++ing.
> Add DevRant client to TiLDA-Mk4

- hologram_demo/main.py
- lib/sim800.py
Added inital GPRS support to sim800
`setup_gprs()` will prepare the sim800 for data, 
`connect_gprs("hologram")` will connect to the hologram APN
Also added a function to start a tcp server on the SIM 800, 
`start_server(4010, callback)` to listen on port 4010, 
the payload will be a binary object passed to whatever function is defined as `callback`
`stop_server()` and` stop_gprs()` will terminate the tcp server and gprs PDP context respectivly
> Sammachin gprs
